---
# file: roles/oracle/tasks/main.yml
- name: Add oracle group
  group:
    name: "{{ item }}"
  with_items:
    - oinstall
    - dba
    - oper

- name: Add oracle user
  user:
    name: oracle
    password: "{{ oracle_password }}"
    group: oinstall
    groups: dba,oper

- name: oracle packages install
  yum:
    name: "{{ item }}"
    state: latest
    enablerepo: "{{ (ansible_distribution == 'RedHat') | ternary('rhel-7-server-optional-rpms','') }}"
  with_items:
    - "{{ oracle_pkg }}"
  register: result
  until: result is success
  retries: 3
  delay: 5

- name: create oracle dir
  file:
    path: "{{ item.path }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    state: directory
  with_items:
    - "{{ oracle_base.paths }}"

- name: check oracle file
  local_action: command ls roles/oracle/files/
  register: st
  changed_when: False

- name: deploy oracle files
  copy:
    src: "{{ item }}"
    dest: "{{ oracle_file_dir }}/"
  become: true
  become_user: oracle
  with_items:
    "{{ st.stdout_lines }}"

- name: extract oracle files
  unarchive:
    src: "{{ oracle_file_dir }}/{{ item }}"
    dest: /home/oracle
    remote_src: true
  args:
    creates: /home/oracle/database/runInstaller
  become: true
  become_user: oracle
  with_items:
    - "{{ st.stdout_lines|sort(reverse=true) }}"

- name: check oracle responsefile version
  shell: grep "^RESPONSEFILE_VERSION" /home/oracle/database/response/dbca.rsp | sed 's/[^"]*"\([^"]*\).*/\1/'
  register: oracle_responsefile
  changed_when: False

- block:
  - name: dot_bash_profile settings
    template:
      src: dot_bash_profile.j2
      dest: /home/oracle/.bash_profile
      owner: oracle
      group: oinstall
      mode: 0644
    register: is_dot_bash_profile_setting

  - name: response file settings
    template:
      src: "{{ item }}.j2"
      dest: "/home/oracle/{{ item }}"
      owner: oracle
      group: oinstall
      mode: 0644
    with_items:
      - db.rsp
      - netca.rsp
    register: is_response_file_setting

  always:
  - name: oracle backup settings
    include_tasks: backup.yml
    with_flattened:
      - "{{ is_dot_bash_profile_setting|default() }}"
      - "{{ is_response_file_setting.results|default() }}"
    loop_control:
      loop_var: backup_item
