---
# file: roles/oracle/tasks/main.yml
- name: Add oracle group
  group:
    name: "{{ item }}"
  with_items:
    - oinstall
    - dba

- name: Add oracle user
  user:
    name: oracle
    password: "{{ oracle_password }}"
    group: oinstall
    groups: dba

- name: oracle packages install
  yum:
    name: "{{ item }}"
    state: present
    enablerepo: "{{ (ansible_distribution == 'RedHat') | ternary('rhel-7-server-optional-rpms','') }}"
  with_items:
    - "{{ oracle_pkg }}"
  register: result
  until: result | success
  retries: 3
  delay: 5

- name: create oracle dir
  file:
    path: "{{ item.path }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    state: directory
  with_items:
    - "{{ oracle_base }}"

- name: /etc/profile.d/enableoracle.sh settings
  template:
    src: enableoracle.sh.j2
    dest: /etc/profile.d/enableoracle.sh
    owner: root
    group: root
    mode: 0644

- name: response file settings
  template:
    src: "{{ item }}.j2"
    dest: "/home/oracle/{{ item }}"
    owner: oracle
    group: oinstall
    mode: 0644
  with_items:
    - db.rsp
    - netca.rsp
