---
# file: roles/oracle-presetup/tasks/main.yml
- name: Add oracle group
  group:
    name={{item}}
  with_items: oracle_group

- name: Add oracle user
  user:
    name="{{item.name}}"
    password="{{item.password}}"
    group="{{item.group}}"
    groups="{{item.groups}}"
    comment="{{item.name}}"
  with_items: oracle_user

- name: packages install
  yum: name={{item}} state=present
  with_items:
    - binutils.x86_64
    - compat-libcap1.x86_64
    - compat-libstdc++-33.x86_64
    - compat-libstdc++-33.i686
    - gcc.x86_64
    - gcc-c++.x86_64
    - glibc.x86_64
    - glibc.i686
    - glibc-devel.x86_64
    - glibc-devel.i686
    - ksh.x86_64
    - libgcc.x86_64
    - libgcc.i686
    - libstdc++.x86_64
    - libstdc++.i686
    - libstdc++-devel.x86_64
    - libstdc++-devel.i686
    - libaio.x86_64
    - libaio.i686
    - libaio-devel.x86_64
    - libaio-devel.i686
    - make.x86_64
    - sysstat.x86_64

- name: oracle install directory
  file: path={{item}} owner=oracle group=oinstall mode=0755 state=directory
  with_items:
    - /opt/oracle
    - /opt/oraInventory

- name: sysctl.conf settings
  template: src=sysctl.conf.j2 dest=/etc/sysctl.conf owner=root group=root mode=0644
  notify: restart sysctl
 
- name: limits.conf settings
  template: src=limits.conf.j2 dest=/etc/security/limits.conf owner=root group=root mode=0644

- name: /etc/pam.d/login settings
  template: src=etc_pam.d_login.j2 dest=/etc/pam.d/login owner=root group=root mode=0644

