---
# file: roles/oracle/defaults/main.yml
proxy_env:
  no_proxy: '*'
#  http_proxy: http://172.16.111.1:8080
#  https_proxy: http://172.16.111.1:8080
oracle_pkg:
  - binutils.x86_64
  - compat-libcap1.x86_64
  - compat-libstdc++-33.x86_64
  - compat-libstdc++-33.i686
  - gcc.x86_64
  - gcc-c++.x86_64
  - glibc.x86_64
  - glibc.i686
  - glibc-devel.x86_64
  - glibc-devel.i686
  - ksh.x86_64
  - libgcc.x86_64
  - libgcc.i686
  - libstdc++.x86_64
  - libstdc++.i686
  - libstdc++-devel.x86_64
  - libstdc++-devel.i686
  - libaio.x86_64
  - libaio.i686
  - libaio-devel.x86_64
  - libaio-devel.i686
  - libXext.x86_64
  - libXext.i686
  - libXtst.x86_64
  - libXtst.i686
  - libX11.x86_64
  - libX11.i686
  - libXau.x86_64
  - libXau.i686
  - libXcb.x86_64
  - libXcb.i686
  - libXi.x86_64
  - libXi.i686
  - make.x86_64
  - sysstat.x86_64
oracle_group:
  - oinstall
  - dba
